Timesheet/src/main/java/haj/com/bean/LookupMenuBean.java
package haj.com.bean;

import java.io.Serializable;

// TODO: Auto-generated Javadoc
/**
 * The Class LookupMenuBean.
 */
public class LookupMenuBean implements Serializable {

	/** The heading. */
	private String heading;
	
	/** The link. */
	private String link;
	
	/**
	 * Instantiates a new lookup menu bean.
	 *
	 * @param heading the heading
	 * @param link the link
	 */
	public LookupMenuBean(String heading, String link) {
		super();
		this.heading = heading;
		this.link = link;
	}
	
	/**
	 * Instantiates a new lookup menu bean.
	 */
	public LookupMenuBean() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	/**
	 * Gets the heading.
	 *
	 * @return the heading
	 */
	public String getHeading() {
		return heading;
	}
	
	/**
	 * Sets the heading.
	 *
	 * @param heading the new heading
	 */
	public void setHeading(String heading) {
		this.heading = heading;
	}
	
	/**
	 * Gets the link.
	 *
	 * @return the link
	 */
	public String getLink() {
		return link;
	}
	
	/**
	 * Sets the link.
	 *
	 * @param link the new link
	 */
	public void setLink(String link) {
		this.link = link;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "LookupMenuBean [heading=" + heading + ", link=" + link + "]";
	}
	
	
	
}

Timesheet/src/main/java/haj/com/entity/BankHolidayParent.java
package haj.com.entity;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import haj.com.framework.IDataEntity;


@Entity
@Table(name = "bank_holiday_parent")
public class BankHolidayParent implements IDataEntity
{
	private static final long serialVersionUID = 1L;
	@Id
    @Column(name="bank_holiday_year",nullable=false)
	private Long bankHolidayYear;
	
	
    @OneToMany(fetch=FetchType.EAGER, mappedBy="bankHolidayParent")
    @OrderBy("bankHoliday ASC")
    @Cascade({CascadeType.SAVE_UPDATE, CascadeType.DELETE})
    private Set<BankHolidayChild> bankHolidayChildrens = new HashSet<BankHolidayChild>(0); 	
	
	
	
	public Long getBankHolidayYear() {
		return bankHolidayYear;
	}
	public void setBankHolidayYear(Long bankHolidayYear) {
		this.bankHolidayYear = bankHolidayYear;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bankHolidayYear == null) ? 0 : bankHolidayYear.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		BankHolidayParent other = (BankHolidayParent) obj;
		if (bankHolidayYear == null) {
			if (other.bankHolidayYear != null)
				return false;
		} else if (!bankHolidayYear.equals(other.bankHolidayYear))
			return false;
		return true;
	}
	
	public Set<BankHolidayChild> getBankHolidayChildrens() {
		return bankHolidayChildrens;
	}
	public void setBankHolidayChildrens(Set<BankHolidayChild> bankHolidayChildrens) {
		this.bankHolidayChildrens = bankHolidayChildrens;
	}

    
	public List<BankHolidayChild> getBankHolidayChildrenList() {
		return new ArrayList<BankHolidayChild>(bankHolidayChildrens);
	}

}

Timesheet/src/main/java/haj/com/entity/Company.java
package haj.com.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import haj.com.billing.entity.Accounts;
import haj.com.framework.IDataEntity;

@Entity
@Table(name = "company")
public class Company implements IDataEntity {
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "company_name", length = 500, nullable = false)
	private String companyName;

	@Column(name = "company_reg_number", length = 100, nullable = true)
	private String companyRegNumber;

	@Column(name = "vat_number", length = 100, nullable = true)
	private String vatNumber;

	@Column(name = "income_tax_number", length = 100, nullable = true)
	private String incomeTaxNumber;

	@Column(name = "logo", length = 200, nullable = true)
	private String logo;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = true)
	private Accounts accounts;
	
	
	private Boolean active;

	@Transient
	private Projects projects;

	public Company() {
		super();
	}

	public Company(Long id) {
		super();
		this.id = id;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyRegNumber() {
		return companyRegNumber;
	}

	public void setCompanyRegNumber(String companyRegNumber) {
		this.companyRegNumber = companyRegNumber;
	}

	public String getVatNumber() {
		return vatNumber;
	}

	public void setVatNumber(String vatNumber) {
		this.vatNumber = vatNumber;
	}

	public String getIncomeTaxNumber() {
		return incomeTaxNumber;
	}

	public void setIncomeTaxNumber(String incomeTaxNumber) {
		this.incomeTaxNumber = incomeTaxNumber;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Accounts getAccounts() {
		return accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	public String getLogo() {
		if (logo != null)
			logo = logo.trim();
		return logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Company other = (Company) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Projects getProjects() {
		return projects;
	}

	public void setProjects(Projects projects) {
		this.projects = projects;
	}


}

Timesheet/src/main/java/haj/com/entity/CompanyUsers.java
package haj.com.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import haj.com.framework.IDataEntity;


@Entity
@Table(name = "company_users")
public class CompanyUsers implements IDataEntity
{
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;


	@ManyToOne(fetch=FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	@JoinColumn(name="user_id", insertable=true, updatable=true, nullable=true)
	private Users users; 
	

	@ManyToOne(fetch=FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	@JoinColumn(name="company_id", insertable=true, updatable=true, nullable=true)
	private Company company;
	
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    private Date createDate;
    
    @Enumerated
    private UsersLevelEnum level;
    
    private Boolean active;


    
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public UsersLevelEnum getLevel() {
		return level;
	}

	public void setLevel(UsersLevelEnum level) {
		this.level = level;
	}
	
	public Boolean getActive() {
		if (active==null) active = Boolean.TRUE;
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CompanyUsers other = (CompanyUsers) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}



}

Timesheet/src/main/java/haj/com/entity/Projects.java
package haj.com.entity;
// Generated Feb 25, 2016 12:09:00 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import haj.com.framework.IDataEntity;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name="projects"
    
)
public class Projects  implements IDataEntity {


     private Long id;
     private String code;
     private String description;
     private Set<TimesheetDetails> timesheetDetailses = new HashSet<TimesheetDetails>(0);
     private Company company;

    public Projects() {
    }

    public Projects(String code, String description, Set<TimesheetDetails> timesheetDetailses) {
       this.code = code;
       this.description = description;
       this.timesheetDetailses = timesheetDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", unique=true , length=100)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projects")
    public Set<TimesheetDetails> getTimesheetDetailses() {
        return this.timesheetDetailses;
    }
    
    public void setTimesheetDetailses(Set<TimesheetDetails> timesheetDetailses) {
        this.timesheetDetailses = timesheetDetailses;
    }

    @ManyToOne(fetch=FetchType.EAGER)
 	@JoinColumn(name="company_id", insertable=true, updatable=true, nullable=true)
	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	private Date createDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "inactive_date", length = 19)
	private Date inactiveDate;
	
	@Column(name = "active")
	private Boolean active;
	
	@Column(name = "overhead")
	private Boolean overhead;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Projects other = (Projects) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Date getInactiveDate() {
		return inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	public Boolean getOverhead() {
		return overhead;
	}

	public void setOverhead(Boolean overhead) {
		this.overhead = overhead;
	}
}

Timesheet/src/main/webapp/admin/bankholidayparent.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core" template="/WEB-INF/template.xhtml">



	<ui:define name="content">
		<div class="ui-g">
			<div class="ui-g-12">
				<div class="card">


					<h:form id="mainForm">
						<h1 class="FontBold">Bank Holidays</h1>
						<div class="EmptyBox10" />
						<p:commandButton id="Insertbankholidayparent" title="Insert New Year" icon="fa fa-plus Fs16 white" oncomplete="PF('dlg').show()" value="Insert" actionListener="#{bankholidayparentUI.prepareNewBankHolidayParent}" update=":bankholidayparentInsForm:bankholidayparentInsGrid" />
						<p:tooltip for="Insertbankholidayparent" />
						<div class="EmptyBox10" />
						<p:growl autoUpdate="true" sticky="false" />
						<h:panelGrid columns="1">


							<p:dataTable var="rowVar" value="#{bankholidayparentUI.bankHolidayParentList}" filteredValue="#{bankholidayparentUI.bankHolidayParentfilteredList}" id="bankholidayparentList" rowKey="#{rowVar.bankHolidayYear}" paginator="true" rows="6" paginatorPosition="bottom"
								paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" rowsPerPageTemplate="5,10,15,20,25" reflow="true" selectionMode="single" selection="#{bankholidayparentUI.bankholidayparent}">

								<p:ajax event="rowSelect" update="childForm" listener="#{bankholidayparentUI.initBankHolidayChild}" />

								<p:column headerText="Year">
									<h:outputText value="#{rowVar.bankHolidayYear}" />
								</p:column>

								<p:column width="5%">

									<p:commandButton id="Deletebankholidayparent" oncomplete="PF('confirmation').show()" icon="fa fa-trash-o Fs16 white" title="Delete Year">
										<f:setPropertyActionListener value="#{rowVar}" target="#{bankholidayparentUI.bankholidayparent}" />
									</p:commandButton>
									<p:tooltip for="Deletebankholidayparent" position="left"/>
								</p:column>



							</p:dataTable>
						</h:panelGrid>






					</h:form>

					<h:form id="childForm">
						<p:outputPanel rendered="#{bankholidayparentUI.bankholidayparent.bankHolidayYear ne null}">
<div class="EmptyBox15"/>
							<div class="ui-g">


								<div class="ui-g-12 ui-md-6">

									<div class="ui-g">


										<div class="ui-g-12 ui-md-6">

											<p:outputLabel for="bhd" value="Bank Holiday" />
										</div>
										<div class="ui-g-12 ui-md-6">
											<p:calendar yearRange="" id="bhd" value="#{bankholidayparentUI.bankHolidayChild.bankHoliday}" pattern="dd MMMM yyyy"></p:calendar>
										</div>
										<div class="ui-g-12 ui-md-6">

											<p:outputLabel value="Holiday Name" />
										</div>
										<div class="ui-g-12 ui-md-6">
											<p:inputText value="#{bankholidayparentUI.bankHolidayChild.holidayNames}" />
										</div>
										<div class="ui-g-12 ui-md-6">
											<p:outputLabel value="Repeat Yearly" />
										</div>
										<div class="ui-g-12 ui-md-6">
											<p:selectBooleanCheckbox value="#{bankholidayparentUI.bankHolidayChild.repeatDates}">
												<p:ajax />
											</p:selectBooleanCheckbox>
										</div>
										<div class="ui-g-12 ui-md-6">






											<p:commandButton id="Searchbankholidayparent" value="Add Holiday" icon="fa fa-plus Fs16 white" title="Add Holiday" action="#{bankholidayparentUI.createChild}" update="@form :mainForm" />
										

										</div>
									</div>
								</div>
								</div>
								<div class="EmptyBox15"/>
								<div class="ui-g">
									<div class="ui-g-12">






										<p:dataTable var="rowVar" value="#{bankholidayparentUI.bankholidayparent.bankHolidayChildrenList}" id="bankholidayparentList" rowKey="#{rowVar.bankHoliday}" paginator="true" rows="10" paginatorPosition="bottom"
											paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" rowsPerPageTemplate="5,10,15,20,25" reflow="true">



											<p:column headerText="Day">
												<h:outputText value="#{rowVar.bankHoliday}" styleClass="#{rowVar.cssStyle}" converter="javax.faces.DateTime" />
											</p:column>
											<p:column headerText="Holiday Name">
												<h:outputText value="#{rowVar.holidayNames}" styleClass="#{rowVar.cssStyle}" />
											</p:column>

											<p:column headerText="Repeat Dates" width="10%" styleClass="texAlCen">

												<p:selectBooleanCheckbox value="#{rowVar.repeatDates}" disabled="true" />
											</p:column>

											<p:column width="5%">

												<p:commandButton title="Delete Holiday Entry" id="delHoliday" icon="fa fa-trash-o Fs16 white" action="#{bankholidayparentUI.bankholidaychildtDelete}" update="@form">
													<f:setPropertyActionListener value="#{rowVar}" target="#{bankholidayparentUI.bankHolidayChild}" />
												</p:commandButton>
												<p:tooltip for="delHoliday" position="left"/>
											</p:column>


										</p:dataTable>
									</div>
								</div>
						</p:outputPanel>

					</h:form>


					<p:confirmDialog message="Are you sure?" width="200" appendTo="@(body)" showEffect="clip" hideEffect="clip" header="Confirm" severity="alert" widgetVar="confirmation">
						<h:form>
							<p:commandButton id="yesbankholidayparent" value="Yes" update=":mainForm:bankholidayparentList" actionListener="#{bankholidayparentUI.bankholidayparentDelete}" oncomplete="PF('confirmation').hide()" />
							<p:tooltip for="yesbankholidayparent" value="(Blue)" />
							<p:commandButton id="nobankholidayparent" value="No" onclick="PF('confirmation').hide()" type="button" />
							<p:tooltip for="nobankholidayparent" value="(Blue)" />
						</h:form>
					</p:confirmDialog>



					<p:dialog modal="true" header="Insert Bank Holiday: Year" widgetVar="dlg" draggable="false" resizable="false" hideEffect="clip" showEffect="clip" id="dialogINS" width="600">

						<h:form id="bankholidayparentInsForm">

							<h:panelGrid columns="2" style="width:100%" id="bankholidayparentInsGrid">

								<p:outputLabel styleClass="Fleft" value="Bank Holiday Year:" for="bankHolidayYear" />

								<p:selectOneMenu id="bankHolidayYear" value="#{bankholidayparentUI.bankholidayparent.bankHolidayYear}" style="width:50%">
									<f:selectItems value="#{bankholidayparentUI.bankHolidayParentDD}" />

								</p:selectOneMenu>



								<p:spacer />
								<p:commandButton id="Submitbankholidayparent" value="Submit" update=":mainForm:bankholidayparentList :bankholidayparentInsForm:bankholidayparentInsGrid" oncomplete="handleInsRequest(xhr, status, args);" actionListener="#{bankholidayparentUI.bankholidayparentInsert}" />
								<p:tooltip for="Submitbankholidayparent" value="" />
							</h:panelGrid>
						</h:form>
					</p:dialog>










					<script type="text/javascript">
						function handleInsRequest(xhr, status, args) {
							if (args.validationFailed) {
								jQuery('#dialogINS').effect("shake", {
									times : 3
								}, 100);
							} else {
								PF('dlg').hide();

							}
						}

						function handleUpdRequest(xhr, status, args) {
							if (args.validationFailed) {
								jQuery('#dialogUPD').effect("shake", {
									times : 3
								}, 100);
							} else {
								PF('dlgUpd').hide();

							}
						}
					</script>
				</div>
			</div>
		</div>

	</ui:define>

</ui:composition>

Timesheet/src/main/webapp/admin/expenseform.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui" xmlns:c="http://java.sun.com/jsp/jstl/core" template="/WEB-INF/template.xhtml">



	<ui:define name="content">

		<div class="ui-g">
			<div class="ui-g-12">
				<div class="card">

					<h:form id="mainform">


						<p:dataTable var="rowVar" value="#{expenseformUI.companyDataModel}" id="companyList" rows="10" lazy="true" reflow="true" paginator="true" paginatorPosition="bottom" paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" rowsPerPageTemplate="10,15,20,35">
							<p:ajax event="rowToggle" listener="#{expenseformUI.toggleCompany(rowVar)}" update="companyList" />
							<p:column style="width:16px">
								<p:rowToggler />
							</p:column>
							<p:column headerText="Company Name">
								<h:outputText value="#{rowVar.companyName}" />
							</p:column>
							<p:rowExpansion>
								<p:dataTable var="rowVar2" value="#{expenseformUI.projectsList}" id="projectList" rows="10" lazy="true" reflow="true" style="border: 1px solid black;" selectionMode="single" selection="#{expenseformUI.projects}" rowKey="#{rowVar2.id}" >
									<p:ajax event="rowSelect" listener="#{expenseformUI.setParameters}"/>
									<f:facet name="header">
										Projects For #{expenseformUI.company.companyName}
									</f:facet>

									<p:column headerText="Project Name">
										<h:outputText value="#{rowVar2.description}" />
									</p:column>
								</p:dataTable>
							</p:rowExpansion>

						</p:dataTable>

					</h:form>

				</div>
			</div>
		</div>


	</ui:define>

</ui:composition>

Timesheet/src/main/webapp/admin/lookupMenu.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">

	<ui:define name="content">
		<style type="text/css">
</style>


		<div class="ui-g">
			<div class="ui-g-12">
			<div class="head-gradient">Lookup Menu</div>
				<h:form id="lookupform">
					<div class="layout-dashboard">


						<p:repeat var="rv" value="#{lookupMenuUI.menus}">
							<div class="ui-g-12 ui-md-4 ui-lg-4">
								<a href="#{request.contextPath}/admin/lookup/#{rv.link}">
									<div class="overview-box views1">
										<div class="overview-numbers">
											#{rv.heading} <br /> <br />
										</div>

									</div>

								</a>
							</div>
						</p:repeat>
					</div>
				</h:form>


			</div>
		</div>
	</ui:define>

</ui:composition>